apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-0
  labels:
    type: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/k8s/mysql-pv-0
    server: 192.168.159.20